// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

package mocks

import (
	"UsersService/internal/entity"
	"context"
	"reflect"

	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecaseInterface is a mock of UsecaseInterface interface.
type MockUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseInterfaceMockRecorder
}

type MockUsecaseInterfaceMockRecorder struct {
	mock *MockUsecaseInterface
}

func NewMockUsecaseInterface(ctrl *gomock.Controller) *MockUsecaseInterface {
	mock := &MockUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockUsecaseInterfaceMockRecorder{mock}
	return mock
}

func (m *MockUsecaseInterface) EXPECT() *MockUsecaseInterfaceMockRecorder {
	return m.recorder
}

func (m *MockUsecaseInterface) AddUser(ctx context.Context, addUserInfo entity.AddUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, addUserInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUsecaseInterfaceMockRecorder) AddUser(ctx, addUserInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUsecaseInterface)(nil).AddUser), ctx, addUserInfo)
}

func (m *MockUsecaseInterface) CompareAuthData(ctx context.Context, users entity.AuthRequest) (*entity.CompareDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareAuthData", ctx, users)
	ret0, _ := ret[0].(*entity.CompareDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) CompareAuthData(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareAuthData", reflect.TypeOf((*MockUsecaseInterface)(nil).CompareAuthData), ctx, users)
}

func (m *MockUsecaseInterface) UpdateUserProfile(ctx context.Context, id uuid.UUID, updateProfileInfo entity.UpdateUserProfileInfoRequest) (*entity.UpdateUserProfileInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, id, updateProfileInfo)
	ret0, _ := ret[0].(*entity.UpdateUserProfileInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) UpdateUserProfile(ctx, id, updateProfileInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUsecaseInterface)(nil).UpdateUserProfile), ctx, id, updateProfileInfo)
}

func (m *MockUsecaseInterface) GetUserProfileByID(ctx context.Context, yourUserID uuid.UUID, otherUserID uuid.UUID) (*entity.ProfileUserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByID", ctx, yourUserID, otherUserID)
	ret0, _ := ret[0].(*entity.ProfileUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) GetUserProfileByID(ctx, yourUserID, otherUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByID", reflect.TypeOf((*MockUsecaseInterface)(nil).GetUserProfileByID), ctx, yourUserID, otherUserID)
}

func (m *MockUsecaseInterface) SubscribeToUser(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUsecaseInterfaceMockRecorder) SubscribeToUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToUser", reflect.TypeOf((*MockUsecaseInterface)(nil).SubscribeToUser), ctx, followerID, followingID)
}

func (m *MockUsecaseInterface) UnsubscribeFromUser(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeFromUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUsecaseInterfaceMockRecorder) UnsubscribeFromUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeFromUser", reflect.TypeOf((*MockUsecaseInterface)(nil).UnsubscribeFromUser), ctx, followerID, followingID)
}

func (m *MockUsecaseInterface) GetSubsUser(ctx context.Context, userID uuid.UUID) (*entity.SubsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubsUser", ctx, userID)
	ret0, _ := ret[0].(*entity.SubsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) GetSubsUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubsUser", reflect.TypeOf((*MockUsecaseInterface)(nil).GetSubsUser), ctx, userID)
}

func (m *MockUsecaseInterface) UploadAvatar(ctx context.Context, userID uuid.UUID, avatarInfo entity.AvatarRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, avatarInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUsecaseInterfaceMockRecorder) UploadAvatar(ctx, userID, avatarInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockUsecaseInterface)(nil).UploadAvatar), ctx, userID, avatarInfo)
}

func (m *MockUsecaseInterface) GlobalSearchPeople(ctx context.Context, firstName, lastName string) (*entity.PersonDateList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalSearchPeople", ctx, firstName, lastName)
	ret0, _ := ret[0].(*entity.PersonDateList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) GlobalSearchPeople(ctx, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalSearchPeople", reflect.TypeOf((*MockUsecaseInterface)(nil).GlobalSearchPeople), ctx, firstName, lastName)
}

func (m *MockUsecaseInterface) GetRefreshToken(ctx context.Context, id uuid.UUID) (*entity.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, id)
	ret0, _ := ret[0].(*entity.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) GetRefreshToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockUsecaseInterface)(nil).GetRefreshToken), ctx, id)
}

func (m *MockUsecaseInterface) UpdateRefreshToken(ctx context.Context, req entity.UpdateRefreshTokenRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUsecaseInterfaceMockRecorder) UpdateRefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockUsecaseInterface)(nil).UpdateRefreshToken), ctx, req)
}

func (m *MockUsecaseInterface) GetUserIDByUsername(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByUsername", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) GetUserIDByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByUsername", reflect.TypeOf((*MockUsecaseInterface)(nil).GetUserIDByUsername), ctx, username)
}

func (m *MockUsecaseInterface) GetAvatarURL(ctx context.Context, bucketName string, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarURL", ctx, bucketName, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUsecaseInterfaceMockRecorder) GetAvatarURL(ctx, bucketName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarURL", reflect.TypeOf((*MockUsecaseInterface)(nil).GetAvatarURL), ctx, bucketName, userID)
}
