global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "zen-clone-services"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "auth_service:8080"
          - "users_service:8081"
          - "post_service:8082"
