// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

package mocks

import (
	"UsersService/internal/entity"
	"context"
	"reflect"

	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryProvider is a mock of RepositoryProvider interface.
type MockRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryProviderMockRecorder
}

type MockRepositoryProviderMockRecorder struct {
	mock *MockRepositoryProvider
}

func NewMockRepositoryProvider(ctrl *gomock.Controller) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockRepositoryProviderMockRecorder{mock}
	return mock
}

func (m *MockRepositoryProvider) EXPECT() *MockRepositoryProviderMockRecorder {
	return m.recorder
}

func (m *MockRepositoryProvider) AddUser(ctx context.Context, addUserInfo entity.AddUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, addUserInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) AddUser(ctx, addUserInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockRepositoryProvider)(nil).AddUser), ctx, addUserInfo)
}

func (m *MockRepositoryProvider) GetUserInfoByLogin(ctx context.Context, login string) (*entity.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByLogin", ctx, login)
	ret0, _ := ret[0].(*entity.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetUserInfoByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByLogin", reflect.TypeOf((*MockRepositoryProvider)(nil).GetUserInfoByLogin), ctx, login)
}

func (m *MockRepositoryProvider) GetUserProfileByUsername(ctx context.Context, username string) (*entity.ProfileUserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByUsername", ctx, username)
	ret0, _ := ret[0].(*entity.ProfileUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetUserProfileByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByUsername", reflect.TypeOf((*MockRepositoryProvider)(nil).GetUserProfileByUsername), ctx, username)
}

func (m *MockRepositoryProvider) GetUserProfileByID(ctx context.Context, userID uuid.UUID) (*entity.ProfileUserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByID", ctx, userID)
	ret0, _ := ret[0].(*entity.ProfileUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetUserProfileByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByID", reflect.TypeOf((*MockRepositoryProvider)(nil).GetUserProfileByID), ctx, userID)
}

func (m *MockRepositoryProvider) UpdateUserProfile(ctx context.Context, id uuid.UUID, updateProfileInfo entity.UpdateUserProfileInfoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, id, updateProfileInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) UpdateUserProfile(ctx, id, updateProfileInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockRepositoryProvider)(nil).UpdateUserProfile), ctx, id, updateProfileInfo)
}

func (m *MockRepositoryProvider) GetUserIdByUsername(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdByUsername", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetUserIdByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdByUsername", reflect.TypeOf((*MockRepositoryProvider)(nil).GetUserIdByUsername), ctx, username)
}

func (m *MockRepositoryProvider) CheckUser(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUser", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) CheckUser(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUser", reflect.TypeOf((*MockRepositoryProvider)(nil).CheckUser), ctx, username)
}

func (m *MockRepositoryProvider) GetLoginByUserID(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginByUserID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetLoginByUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginByUserID", reflect.TypeOf((*MockRepositoryProvider)(nil).GetLoginByUserID), ctx, id)
}

func (m *MockRepositoryProvider) GlobalSearchPeople(ctx context.Context, firstName, lastName string, bucketName string) (*entity.PersonDateList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalSearchPeople", ctx, firstName, lastName, bucketName)
	ret0, _ := ret[0].(*entity.PersonDateList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GlobalSearchPeople(ctx, firstName, lastName, bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalSearchPeople", reflect.TypeOf((*MockRepositoryProvider)(nil).GlobalSearchPeople), ctx, firstName, lastName, bucketName)
}

func (m *MockRepositoryProvider) UpdateRefreshToken(ctx context.Context, id uuid.UUID, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", ctx, id, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) UpdateRefreshToken(ctx, id, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockRepositoryProvider)(nil).UpdateRefreshToken), ctx, id, refreshToken)
}

func (m *MockRepositoryProvider) GetRefreshTokenByUserID(ctx context.Context, id uuid.UUID) (*entity.RefreshTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByUserID", ctx, id)
	ret0, _ := ret[0].(*entity.RefreshTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetRefreshTokenByUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByUserID", reflect.TypeOf((*MockRepositoryProvider)(nil).GetRefreshTokenByUserID), ctx, id)
}

func (m *MockRepositoryProvider) SubscribeFromUser(ctx context.Context, followerID, followingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeFromUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) SubscribeFromUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeFromUser", reflect.TypeOf((*MockRepositoryProvider)(nil).SubscribeFromUser), ctx, followerID, followingID)
}

func (m *MockRepositoryProvider) UnsubscribeFromUser(ctx context.Context, followerID, followingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeFromUser", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) UnsubscribeFromUser(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeFromUser", reflect.TypeOf((*MockRepositoryProvider)(nil).UnsubscribeFromUser), ctx, followerID, followingID)
}

func (m *MockRepositoryProvider) GetSubsUser(ctx context.Context, userID uuid.UUID, bucketName string) (*entity.SubsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubsUser", ctx, userID, bucketName)
	ret0, _ := ret[0].(*entity.SubsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetSubsUser(ctx, userID, bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubsUser", reflect.TypeOf((*MockRepositoryProvider)(nil).GetSubsUser), ctx, userID, bucketName)
}

func (m *MockRepositoryProvider) CheckSubscription(ctx context.Context, followerID string, followingID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSubscription", ctx, followerID, followingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) CheckSubscription(ctx, followerID, followingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSubscription", reflect.TypeOf((*MockRepositoryProvider)(nil).CheckSubscription), ctx, followerID, followingID)
}

func (m *MockRepositoryProvider) GetAvatarURL(ctx context.Context, bucketName string, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarURL", ctx, bucketName, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetAvatarURL(ctx, bucketName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarURL", reflect.TypeOf((*MockRepositoryProvider)(nil).GetAvatarURL), ctx, bucketName, userID)
}

func (m *MockRepositoryProvider) UploadAvatar(ctx context.Context, userID uuid.UUID, bucketName string, avatarInfo entity.AvatarRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, bucketName, avatarInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) UploadAvatar(ctx, userID, bucketName, avatarInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockRepositoryProvider)(nil).UploadAvatar), ctx, userID, bucketName, avatarInfo)
}
