// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../../mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	usersclient "AuthService/internal/client/usersclient"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientProvider is a mock of ClientProvider interface.
type MockClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClientProviderMockRecorder
	isgomock struct{}
}

// MockClientProviderMockRecorder is the mock recorder for MockClientProvider.
type MockClientProviderMockRecorder struct {
	mock *MockClientProvider
}

// NewMockClientProvider creates a new mock instance.
func NewMockClientProvider(ctrl *gomock.Controller) *MockClientProvider {
	mock := &MockClientProvider{ctrl: ctrl}
	mock.recorder = &MockClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientProvider) EXPECT() *MockClientProviderMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockClientProvider) AddUser(ctx context.Context, userData usersclient.RegisterRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockClientProviderMockRecorder) AddUser(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockClientProvider)(nil).AddUser), ctx, userData)
}

// CompareAuthData mocks base method.
func (m *MockClientProvider) CompareAuthData(ctx context.Context, userData usersclient.AuthRequest) (*usersclient.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareAuthData", ctx, userData)
	ret0, _ := ret[0].(*usersclient.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareAuthData indicates an expected call of CompareAuthData.
func (mr *MockClientProviderMockRecorder) CompareAuthData(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareAuthData", reflect.TypeOf((*MockClientProvider)(nil).CompareAuthData), ctx, userData)
}

// GetRefreshToken mocks base method.
func (m *MockClientProvider) GetRefreshToken(ctx context.Context, token usersclient.TokenRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockClientProviderMockRecorder) GetRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockClientProvider)(nil).GetRefreshToken), ctx, token)
}

// UpdateRefreshToken mocks base method.
func (m *MockClientProvider) UpdateRefreshToken(ctx context.Context, req usersclient.UpdateRefreshTokenRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockClientProviderMockRecorder) UpdateRefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockClientProvider)(nil).UpdateRefreshToken), ctx, req)
}
