// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

package mocks

import (
	"context"
	"reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducerProvider is a mock of ProducerProvider interface.
type MockProducerProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProducerProviderMockRecorder
}

type MockProducerProviderMockRecorder struct {
	mock *MockProducerProvider
}

func NewMockProducerProvider(ctrl *gomock.Controller) *MockProducerProvider {
	mock := &MockProducerProvider{ctrl: ctrl}
	mock.recorder = &MockProducerProviderMockRecorder{mock}
	return mock
}

func (m *MockProducerProvider) EXPECT() *MockProducerProviderMockRecorder {
	return m.recorder
}

func (m *MockProducerProvider) WriteMessages(ctx context.Context, key string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessages", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockProducerProviderMockRecorder) WriteMessages(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockProducerProvider)(nil).WriteMessages), ctx, key, value)
}
