// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

package mocks

import (
	"PostService/internal/entity"
	"context"
	"reflect"

	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryProvider is a mock of RepositoryProvider interface.
type MockRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryProviderMockRecorder
}

type MockRepositoryProviderMockRecorder struct {
	mock *MockRepositoryProvider
}

func NewMockRepositoryProvider(ctrl *gomock.Controller) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockRepositoryProviderMockRecorder{mock}
	return mock
}

func (m *MockRepositoryProvider) EXPECT() *MockRepositoryProviderMockRecorder {
	return m.recorder
}

func (m *MockRepositoryProvider) CreatePost(ctx context.Context, createPost entity.CreatePostResponse) (*entity.CreatePostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, createPost)
	ret0, _ := ret[0].(*entity.CreatePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) CreatePost(ctx, createPost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockRepositoryProvider)(nil).CreatePost), ctx, createPost)
}

func (m *MockRepositoryProvider) UpdatePost(ctx context.Context, postID uuid.UUID, authorID uuid.UUID, updateReq entity.UpdateUserPostRequest) (*entity.UpdateUserPostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, postID, authorID, updateReq)
	ret0, _ := ret[0].(*entity.UpdateUserPostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) UpdatePost(ctx, postID, authorID, updateReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockRepositoryProvider)(nil).UpdatePost), ctx, postID, authorID, updateReq)
}

func (m *MockRepositoryProvider) DeletePost(ctx context.Context, postID uuid.UUID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, postID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryProviderMockRecorder) DeletePost(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockRepositoryProvider)(nil).DeletePost), ctx, postID, userID)
}

func (m *MockRepositoryProvider) GetPostsUser(ctx context.Context, authorID uuid.UUID, limit int, cursor *entity.PostCursor) (*entity.PostListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsUser", ctx, authorID, limit, cursor)
	ret0, _ := ret[0].(*entity.PostListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetPostsUser(ctx, authorID, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsUser", reflect.TypeOf((*MockRepositoryProvider)(nil).GetPostsUser), ctx, authorID, limit, cursor)
}

func (m *MockRepositoryProvider) GetPostsFromFeed(ctx context.Context, authorIDs []uuid.UUID, limit int, cursor *entity.PostCursor) (*entity.PostListResponseFromFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsFromFeed", ctx, authorIDs, limit, cursor)
	ret0, _ := ret[0].(*entity.PostListResponseFromFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryProviderMockRecorder) GetPostsFromFeed(ctx, authorIDs, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsFromFeed", reflect.TypeOf((*MockRepositoryProvider)(nil).GetPostsFromFeed), ctx, authorIDs, limit, cursor)
}
