// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

package mocks

import (
	"PostService/internal/client/subsclient"
	"context"
	"reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientProvider is a mock of subsclient.ClientProvider interface.
type MockClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClientProviderMockRecorder
}

type MockClientProviderMockRecorder struct {
	mock *MockClientProvider
}

func NewMockClientProvider(ctrl *gomock.Controller) *MockClientProvider {
	mock := &MockClientProvider{ctrl: ctrl}
	mock.recorder = &MockClientProviderMockRecorder{mock}
	return mock
}

func (m *MockClientProvider) EXPECT() *MockClientProviderMockRecorder {
	return m.recorder
}

func (m *MockClientProvider) GetSubsUser(ctx context.Context, username string, accessToken string) (*subsclient.SubsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubsUser", ctx, username, accessToken)
	ret0, _ := ret[0].(*subsclient.SubsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockClientProviderMockRecorder) GetSubsUser(ctx, username, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubsUser", reflect.TypeOf((*MockClientProvider)(nil).GetSubsUser), ctx, username, accessToken)
}

func (m *MockClientProvider) GetUserProfileByUsername(ctx context.Context, username string, accessToken string) (*subsclient.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByUsername", ctx, username, accessToken)
	ret0, _ := ret[0].(*subsclient.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockClientProviderMockRecorder) GetUserProfileByUsername(ctx, username, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByUsername", reflect.TypeOf((*MockClientProvider)(nil).GetUserProfileByUsername), ctx, username, accessToken)
}
