// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

package mocks

import (
	"PostService/internal/entity"
	"context"
	"reflect"

	"github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCaseInterface is a mock of UseCaseInterface interface.
type MockUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseInterfaceMockRecorder
}

type MockUseCaseInterfaceMockRecorder struct {
	mock *MockUseCaseInterface
}

func NewMockUseCaseInterface(ctrl *gomock.Controller) *MockUseCaseInterface {
	mock := &MockUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockUseCaseInterfaceMockRecorder{mock}
	return mock
}

func (m *MockUseCaseInterface) EXPECT() *MockUseCaseInterfaceMockRecorder {
	return m.recorder
}

func (m *MockUseCaseInterface) CreatePost(ctx context.Context, creatorUserID uuid.UUID, createPost entity.CreatePostRequest) (*entity.CreatePostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, creatorUserID, createPost)
	ret0, _ := ret[0].(*entity.CreatePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUseCaseInterfaceMockRecorder) CreatePost(ctx, creatorUserID, createPost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockUseCaseInterface)(nil).CreatePost), ctx, creatorUserID, createPost)
}

func (m *MockUseCaseInterface) UpdatePost(ctx context.Context, postID uuid.UUID, authorID uuid.UUID, updateReq entity.UpdateUserPostRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, postID, authorID, updateReq)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUseCaseInterfaceMockRecorder) UpdatePost(ctx, postID, authorID, updateReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockUseCaseInterface)(nil).UpdatePost), ctx, postID, authorID, updateReq)
}

func (m *MockUseCaseInterface) DeletePost(ctx context.Context, postID uuid.UUID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, postID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockUseCaseInterfaceMockRecorder) DeletePost(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockUseCaseInterface)(nil).DeletePost), ctx, postID, userID)
}

func (m *MockUseCaseInterface) GetPostsUser(ctx context.Context, authorID uuid.UUID, limit int, cursor *entity.PostCursor) (*entity.PostListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsUser", ctx, authorID, limit, cursor)
	ret0, _ := ret[0].(*entity.PostListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUseCaseInterfaceMockRecorder) GetPostsUser(ctx, authorID, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsUser", reflect.TypeOf((*MockUseCaseInterface)(nil).GetPostsUser), ctx, authorID, limit, cursor)
}

func (m *MockUseCaseInterface) GetPostsFromFeed(ctx context.Context, userUsername string, userID uuid.UUID, accessToken string, limit int, cursor *entity.PostCursor) (*entity.PostListResponseFromFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsFromFeed", ctx, userUsername, userID, accessToken, limit, cursor)
	ret0, _ := ret[0].(*entity.PostListResponseFromFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUseCaseInterfaceMockRecorder) GetPostsFromFeed(ctx, userUsername, userID, accessToken, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsFromFeed", reflect.TypeOf((*MockUseCaseInterface)(nil).GetPostsFromFeed), ctx, userUsername, userID, accessToken, limit, cursor)
}
